name: Build, Tests and Examples

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn build
      - run: yarn test
      - run: yarn test-with-node
      - run: yarn examples-with-node
